"""empty message

Revision ID: 73e6fea9723c
Revises: cc374dceade3
Create Date: 2019-07-03 01:39:33.863473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e6fea9723c'
down_revision = 'cc374dceade3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'score')
    # ### end Alembic commands ###
